disabled_rules: # rule identifiers to exclude from running
#  - colon
#  - comma
#  - control_statement
#  - file_length
#  - force_cast
#  - force_try
#  - function_body_length
#  - leading_whitespace
- line_length
- nesting
- large_tuple
- notification_center_detachment
#  - opening_brace
#  - operator_whitespace
#  - return_arrow_whitespace
#  - statement_position
#  - todo
#  - trailing_newline
#  - trailing_semicolon
#  - trailing_whitespace
#  - type_body_length
#  - type_name
#  - variable_name_max_length
#  - variable_name_min_length
- identifier_name
included: # paths to include during linting. `--path` is ignored if present. takes precendence over `excluded`.
excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - Pods

file_length:
  - 1000
function_body_length:
  - 75
  - 100
type_body_length:
  - 400 # Warning
  - 500 # Error
function_parameter_count:
  - 15
  - 25
cyclomatic_complexity:
 - 30
 - 50
type_name:
 min_length: 3
 max_length: 60
 excluded:
  - T
  - U